import { getAgentByName, routeAgentRequest } from "agents";
import { createWorkersAI } from "workers-ai-provider";
import { Think } from "@cloudflare/think";
import {
	defineMessengers,
	ThinkMessengerStateAgent,
	type ThinkMessengers,
} from "@cloudflare/think/messengers";
import telegramMessenger from "@cloudflare/think/messengers/telegram";

// Think keeps Chat SDK bookkeeping (thread subscriptions, locks, queues) in
// this helper agent. Re-export it so the framework can route to it. We never
// call it directly, and it needs no binding/migration of its own in production.
export { ThinkMessengerStateAgent };

// `Env` is generated by `wrangler types` into worker-configuration.d.ts:
// bindings (AI, ChatAgent) come from wrangler.jsonc; secret names come from
// the `secrets.required` list there. No hand-written types needed.

const AGENT_NAME = "default"; // single shared conversation instance
const TELEGRAM_WEBHOOK_PATH = "/messengers/telegram/webhook";

export class ChatAgent extends Think<Env> {
	// 1) WHICH MODEL answers — Workers AI, via the AI binding.
	override getModel() {
		return createWorkersAI({ binding: this.env.AI })(
			"@cf/moonshotai/kimi-k2.6",
		);
	}

	// 2) THE PERSONALITY.
	override getSystemPrompt() {
		return [
			"You are a friendly, concise assistant replying inside a Telegram chat.",
			"Keep answers short and easy to read on a phone.",
		].join("\n");
	}

	// 3) WHICH MESSENGERS feed this agent. Just Telegram here.
	override getMessengers(): ThinkMessengers {
		return defineMessengers({
			telegram: telegramMessenger({
				token: this.env.TELEGRAM_BOT_TOKEN,
				userName: this.env.TELEGRAM_BOT_USERNAME,
				secretToken: this.env.TELEGRAM_WEBHOOK_SECRET_TOKEN,
				// "self" = every chat shares ONE memory (simplest). Remove this line
				// to give each Telegram thread its own isolated sub-agent + memory.
				conversation: "self",
				respondTo: ["direct-message", "mention"],
			}),
		});
	}
}

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		// Framework routes first (the agent's own /agents/* endpoints).
		const agentResponse = await routeAgentRequest(request, env);
		if (agentResponse) return agentResponse;

		const url = new URL(request.url);
		const agent = await getAgentByName(env.ChatAgent, AGENT_NAME);

		// Telegram posts updates here → hand them to the agent. Think verifies the
		// secret, converts the update into a chat turn, and streams a reply back.
		if (url.pathname === TELEGRAM_WEBHOOK_PATH) {
			return agent.fetch(request);
		}

		// Convenience route: tell Telegram to deliver updates to THIS URL.
		if (
			request.method === "POST" &&
			url.pathname === "/setup/telegram-webhook"
		) {
			// Force https: behind a tunnel the Worker sees the forwarded request as
			// http, but Telegram requires an HTTPS webhook (the public host is correct).
			const webhookUrl = `https://${url.host}${TELEGRAM_WEBHOOK_PATH}`;
			const res = await fetch(
				`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/setWebhook`,
				{
					method: "POST",
					headers: { "content-type": "application/json" },
					body: JSON.stringify({
						url: webhookUrl,
						secret_token: env.TELEGRAM_WEBHOOK_SECRET_TOKEN,
						allowed_updates: ["message"],
						drop_pending_updates: true,
					}),
				},
			);
			return Response.json(
				{ ok: res.ok, webhookUrl, result: await res.json() },
				{ status: res.ok ? 200 : 502 },
			);
		}

		// Anything else → a tiny status page.
		return Response.json({
			name: "chat-agent",
			webhook: TELEGRAM_WEBHOOK_PATH,
			setup: "POST /setup/telegram-webhook",
		});
	},
} satisfies ExportedHandler<Env>;
